### PR TITLE
pancontrol.py: Added support for arm64 platforms

### PR DESCRIPTION
**Pull request by LanderU**

### CODE REVIEW

**Comment by AntumDeluge** [comment]
Thank you. This has been merged to the ['unstable' branch](https://github.com/AntumDeluge/debreate/commit/aa7ce4de1bd11f561e0493545c7e8671c1156f7a).

**Comment by AntumDeluge** [comment]
Just wanted to let you know that I destroyed the commit history & started with a fresh branch so that I could attribute commits from my old Subversion repository. So you will probably want to re-fork. The old history is on [old-unstable branch](https://github.com/AntumDeluge/debreate/tree/old-unstable), but I won't be committing to that anymore. The new history is in [unstable](https://github.com/AntumDeluge/debreate/tree/unstable), which is now the default branch.

**Comment by LanderU** [comment]
Hi @AntumDeluge,

thanks! If you wish I can help you with this amazing project!

**Comment by AntumDeluge** [comment]
Your help is much appreciated.

I must apologize in advance though, I am not always active with the project, as I have many other projects that I work on. And not all of them involve software. So at times, I am hard to reach. I am also very introverted & not always a good communicator. So I'm sorry if I don't get back to you right away about issues.

If you use IRC, I am sometimes found on the [#debreate](https://webchat.freenode.net/?channels=#debreate) channel on the [Freenode network](http://freenode.net/).

**Comment by LanderU** [comment]
I understand perfectly, do not worry. Thanks for your job!

**Pull request closed without merging**
